DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    file_name TEXT NOT NULL,
    img BLOB NOT NULL,
    content TEXT NOT NULL,
    extension TEXT NOT NULL
);

DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_alias TEXT NOT NULL,
    content TEXT NOT NULL,
    associated_post INT NOT NULL REFERENCES posts(id) DEFAULT 0
);

