DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    filename VARCHAR(37),
    content TEXT NOT NULL,
    associated_image INT NOT NULL REFERENCES pics(id) DEFAULT 0
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_alias TEXT NOT NULL,
    content TEXT NOT NULL,
    associated_image INT NOT NULL REFERENCES posts(id) DEFAULT 0
);
